File `lib-trunk/VERSION` no longer required for installation (use `jq` instead)

diff --git a/Makefile_install_lib b/Makefile_install_lib
--- a/Makefile_install_lib
+++ b/Makefile_install_lib
@@ -46,5 +46,18 @@ $(PAKCS_CURRY_FILES): %.curry: $(CURRYLIBSSRCDIR)/%.curry %.pakcs
 $(PAKCS_PL_FILES): %.pakcs.pl: $(CURRYLIBSSRCDIR)/%.pakcs.pl
 	cp $< $@
 
-$(LIBDIR)/VERSION: $(CURRYLIBSDIR)/VERSION
-	cp $< $@
+$(LIBDIR)/VERSION: require-jq $(CURRYLIBSDIR)/package.json
+	$(JQ) -r '.version' $(CURRYLIBSDIR)/package.json > $@
+
+############################################################################
+# Executable of JSON command-line processor:
+JQ := $(shell which jq)
+
+.PHONY: require-jq
+require-jq:
+	@if [ ! -x "$(JQ)" ] ; then \
+		echo "Tool 'jq' not found!" ; \
+		echo "Install it, e.g.,  by 'sudo apt install jq'" ; \
+		exit 1 ; fi
+
+############################################################################
